listener {
    timeout = 120
    on-timeout = hyprctl dispatch 'hl.dsp.dpms("off")'
    on-resume  = hyprctl dispatch 'hl.dsp.dpms("on")'
}

listener {
    timeout = 240
    on-timeout = hyprlock
}

listener {
    timeout = 240
    on-timeout = brightnessctl -s -d dell::kbd_backlight && brightnessctl -d dell::kbd_backlight set 0
    on-resume = brightnessctl -r -d dell::kbd_backlight
}

listener {
    timeout = 300
    on-timeout = systemctl suspend
}
