[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
# padding = { x = 1, y = 1 }
dynamic_padding = true 
decorations = "None"
opacity = 0.85

# [env]
# TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 16.0

[general]
import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

