name: Lint Markdown Files

on:
  push:
    paths:
      - '**/*.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install markdownlint
        run: npm install -g markdownlint-cli  # Instalacja markdownlint-cli

      - name: Run markdownlint
        run: markdownlint '**/*.md'  # Uruchomienie markdownlint na plikach .md
